"""empty message

Revision ID: 0ba2726eba35
Revises: 14206916d48b
Create Date: 2023-04-12 15:46:16.640250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba2726eba35'
down_revision = '14206916d48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wise_key', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wise_key')
    # ### end Alembic commands ###
