"""empty message

Revision ID: 231cf710704b
Revises: 0ba2726eba35
Create Date: 2023-04-19 11:13:32.278705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231cf710704b'
down_revision = '0ba2726eba35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jacket', sa.Column('pic_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jacket', 'pic_hash')
    # ### end Alembic commands ###
