"""empty message

Revision ID: 654a2e7b72d6
Revises: 81bbeb1d63df
Create Date: 2023-04-12 12:40:22.671910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654a2e7b72d6'
down_revision = '81bbeb1d63df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=255), nullable=False),
    sa.Column('recipient_id', sa.String(length=255), nullable=False),
    sa.Column('transfer_id', sa.String(length=255), nullable=False),
    sa.Column('target_account_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('shopping_cart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jacket', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('shopping_cart', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart', 'amount')
    op.drop_column('jacket', 'price')
    op.drop_table('transactions')
    # ### end Alembic commands ###
