"""empty message

Revision ID: 81bbeb1d63df
Revises: 1403b9cca3c4
Create Date: 2023-04-11 12:50:22.214064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bbeb1d63df'
down_revision = '1403b9cca3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_cart_jackets',
    sa.Column('shopping_cart_id', sa.Integer(), nullable=False),
    sa.Column('jacket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jacket_id'], ['jacket.id'], ),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_cart.id'], ),
    sa.PrimaryKeyConstraint('shopping_cart_id', 'jacket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart_jackets')
    op.drop_table('shopping_cart')
    # ### end Alembic commands ###
